name: Update README year

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-year:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update year in README
        run: |
          current_year=$(date +'%Y')
          sed -i "s/- ðŸ¥… [0-9]\{4\} Goals:/- ðŸ¥… ${current_year} Goals:/g" README.md

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          current_year=$(date +'%Y')
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: update goals year to ${current_year}"
          git push
